name: Blacken

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  blacken:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install dependencies and Black
        run: |
          pip install -r requirements.txt
          pip install black
        
      - name: Run black --check .
        run: black --check .
        
      - name: Run black if need be
        if: failure()
        run: black .
        
      - name: Commit black changes to the repository
        if: failure()
        uses: EndBug/add-and-commit@v7
        with:
          message: 'format and ${{ github.event.head_commit.message }}'
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
