name: Blacken

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install dependencies and Black
        run: |
          pip install -r requirements.txt
          pip install black
        
      - name: Run black --check .
        run: black --check .
        
      - name: If needed, commit black changes to the pull request
        if: failure()
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'style code to match standards'
